language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "nightly"
  - "pypy"
  - "pypy3"

matrix:
  allow_failures:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "nightly"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: python setup.py test
